[project]
name = "probo-playground"
version = "0.1.0"
description = "A simulation environment for a mobile robot operating in two dimensions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "pytest",
    "PyYAML",
]

[tool.pytest.ini_options]
testpaths = ["test"]